# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8bbeb6cb9fc0a75274c206d127adf7c7e67e03ba859c8f000694cecffb093f4d845c7c385314ea5a4e37a31467d84d553179453fdd9ece732f70a2e830640b7b

test:
  secret_key_base: d86417acbd8c582dc5f42fabe09835e65c84a0abbd8331a8bd22156aca8689e5f4f7d33e0cae7349017411dbf9af347c0e0860eb67ae8c28a3ec2d380fa725a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
